### ISSUE TITLE
Back propagation when using mini-batching

### ISSUE THREAD

**Issue by mtk12585** [2019-dl-training-program/Lab1#1]
Hi 助教大大,
這次實作backpropagation時遇到一個問題：如果使用mini-batching的話，要怎麼合併一個mini-batch中，每筆data的gradient？

本來是想說，既然loss是把一個batch中每筆data的loss加起來平均，那把cost對output-layer-activation的gradient也加起來平均好了，所以就變成每個mini-batch進行的update都是把output-layer的gradient加起來平均後，再丟進去backpropagation

不過後來google到的作法好像是把每筆data的loss對每個weight的gradient加起來做平均，比如[這裡](https://stats.stackexchange.com/questions/266968/how-does-minibatch-gradient-descent-update-the-weights-for-each-example-in-a-bat)

想請問助教是否有關這方面的建議或者參考資料

感謝感謝!

**Comment by zivzone** [comment]
HIHI @mtk12585 可以參考這個連結:
https://blog.csdn.net/cs24k1993/article/details/79120579
